GET /rest/api/employees 
Host: localhost:8080

###
POST /rest/api/employees
Host: localhost:8080
Content-Type: custom/type

Employee [id=5, name=mariem, salary=10]

###
GET /rest/api/date/tomorrow
Host: localhost:8080

###
GET /rest/api/categories
Host: localhost:8080

###
GET /api/api/categories
Host: localhost:8181

###
POST /rest/api/categories
Host: localhost:8181
Content-Type: applicatoin/json

{"name":"anotherTestCategory"}



###
POST /rest/api/categories
Host: localhost:8080
Content-Type: applicatoin/json

{"name":"testCategory"}

###
GET /rest/api/products
Host: localhost:8080



###
GET /api/api/products
Host: localhost:8181

###
GET  /api/api/products/152
Host: localhost:8181



###
POST /api/api/products/152/categories/2
Host: localhost:8181

###
DELETE /api/api/categories/2
Host: localhost:8181



###
POST /rest/api/products/1
Host: localhost:8080
Content-Type: application/json

{
    "name":"product2",
    "description":"test product",
    "price":500
}

###
PUT /rest/api/products/1
Host: localhost:8181
Content-Type: application/json

{
    "name":"product2",
    "description":"test product",
    "price":500
}

###
PUT /rest/api/products/1
Host: localhost:8181
Content-Type: application/json

{
    "name":"IntellijIdeaUltimate",
    "description":"updated product",
    "price":8977854
}


###
POST  /rest/api/products/53/categories/
Host: localhost:8181
Content-Type: application/json

{
    "name":"product2",
    "description":"updated product",
    "price":8977854
}



###
GET /api/api/users
Host: localhost:8181
Accept: application/json



###
GET /api/api/users
Host: localhost:8181
Accept: application/json

###
POST /api/api/users
Host: localhost:8181
Content-Type: application/json

{
    "firstName":"mario",
    "lastName":"super",
    "email":"mariooo@gmail.com",
    "role":"ADMIN"
}



###
PUT  /api/api/users/52
Host: localhost:8181
Content-Type: application/json

{
    "firstName":"marieeeeeeeeeeeem",
    "lastName":"hooolaaaa",
    "email":"ooo@gmail.com",
    "role":"ADMIN"
}


###
DELETE  /api/api/users/53
Host: localhost:8181


###
GET  /api/api/users/1/cart
Host: localhost:8181



###
DELETE   /api/api/users/1/cart/1
Host: localhost:8181



###
POST  /api/api/users/1/cart
Host: localhost:8181
Content-Type: application/json

{
    "productId": 1,
    "quantity":50
}


###
POST /api/api/users/1/orders
Host: localhost:8181


###
GET /api/api/users/1/orders
Host: localhost:8181


###
GET /api/api/orders/1
Host: localhost:8181


###
PUT /api/api/orders/1
Host: localhost:8181
Content-Type: application/json

{
    "status":"CANCELED"
}


###
PUT /rest/api/users/153
Host: localhost:8080
Content-Type: application/json

{
    "firstName":"XXXXXXXXXXXX",
    "lastName":"mohamed",
    "email":"mariem@gmail.com"
}



###
DELETE /rest/api/users/153
Host: localhost:8080
Content-Type: application/json