GET /rest/api/employees 
Host: localhost:8080

###
POST /rest/api/employees
Host: localhost:8080
Content-Type: custom/type

Employee [id=5, name=mariem, salary=10]

###
GET /rest/api/date/tomorrow
Host: localhost:8080

###
GET /rest/api/categories
Host: localhost:8080

###
POST /rest/api/categories
Host: localhost:8080
Content-Type: applicatoin/json

{"name":"testCategory"}

###
GET /rest/api/products
Host: localhost:8080



###
GET /rest/api/products
Host: localhost:8181

###
DELETE  /rest/api/products/1
Host: localhost:8181



###
DELETE /rest/api/products/1/categories/1
Host: localhost:8181



###
POST /rest/api/products
Host: localhost:8080
Content-Type: application/json

{
    "name":"product2",
    "description":"test product",
    "price":500
}

###
POST /rest/api/products
Host: localhost:8181
Content-Type: application/json

{
    "name":"product2",
    "description":"test product",
    "price":500
}

###
PUT /rest/api/products/1
Host: localhost:8181
Content-Type: application/json

{
    "name":"IntellijIdeaUltimate",
    "description":"updated product",
    "price":8977854
}


###
POST  /rest/api/products/53/categories/
Host: localhost:8181
Content-Type: application/json

{
    "name":"product2",
    "description":"updated product",
    "price":8977854
}




###
GET /rest/api/users
Host: localhost:8080


###
POST /rest/api/users
Host: localhost:8080
Content-Type: application/json

{
    "firstName":"mariem",
    "lastName":"mohamed",
    "email":"mariem@gmail.com",
    "role":"CUSTOMER"
}



###
PUT /rest/api/users/153
Host: localhost:8080
Content-Type: application/json

{
    "firstName":"XXXXXXXXXXXX",
    "lastName":"mohamed",
    "email":"mariem@gmail.com"
}



###
DELETE /rest/api/users/153
Host: localhost:8080
Content-Type: application/json